export const BREED_DATA = [
  {
    id: 'labrador',
    name: 'Labrador Retriever',
    group: 'Sporting',
    size: 'Large',
    weight: '55-80 lbs',
    lifespan: '10-12 years',
    energy: 'High',
    iconColor: '#F4A261',
    description: 'Friendly, active, and outgoing. America\'s most popular breed.',
    healthRisks: [
      { condition: 'Hip Dysplasia', severity: 'common', description: 'Joint condition causing lameness and arthritis' },
      { condition: 'Elbow Dysplasia', severity: 'common', description: 'Developmental abnormality of the elbow joint' },
      { condition: 'Obesity', severity: 'common', description: 'Labs love food - weight management is crucial' },
      { condition: 'Progressive Retinal Atrophy', severity: 'moderate', description: 'Degenerative eye disease leading to blindness' },
      { condition: 'Exercise-Induced Collapse', severity: 'moderate', description: 'Genetic condition causing collapse after exercise' },
    ],
    careNotes: 'Needs daily exercise and mental stimulation. Watch food intake closely. Regular joint supplements may help.',
  },
  {
    id: 'german-shepherd',
    name: 'German Shepherd',
    group: 'Herding',
    size: 'Large',
    weight: '50-90 lbs',
    lifespan: '9-13 years',
    energy: 'High',
    iconColor: '#8B6914',
    description: 'Intelligent, loyal, and versatile working dog.',
    healthRisks: [
      { condition: 'Hip Dysplasia', severity: 'common', description: 'Very common in the breed - affects mobility' },
      { condition: 'Degenerative Myelopathy', severity: 'moderate', description: 'Progressive spinal cord disease' },
      { condition: 'Bloat (GDV)', severity: 'serious', description: 'Life-threatening stomach condition' },
      { condition: 'Elbow Dysplasia', severity: 'common', description: 'Joint malformation causing lameness' },
      { condition: 'Allergies', severity: 'moderate', description: 'Skin and food allergies are common' },
    ],
    careNotes: 'Avoid exercise right after meals to reduce bloat risk. Regular hip/elbow screening recommended.',
  },
  {
    id: 'golden-retriever',
    name: 'Golden Retriever',
    group: 'Sporting',
    size: 'Large',
    weight: '55-75 lbs',
    lifespan: '10-12 years',
    energy: 'High',
    iconColor: '#D4793A',
    description: 'Gentle, intelligent, and devoted family companion.',
    healthRisks: [
      { condition: 'Cancer', severity: 'serious', description: 'Higher cancer rates than most breeds' },
      { condition: 'Hip Dysplasia', severity: 'common', description: 'Joint condition common in large breeds' },
      { condition: 'Heart Disease', severity: 'moderate', description: 'Subvalvular aortic stenosis can occur' },
      { condition: 'Skin Conditions', severity: 'common', description: 'Hot spots and allergies are frequent' },
      { condition: 'Cataracts', severity: 'moderate', description: 'Eye condition that can cause vision loss' },
    ],
    careNotes: 'Regular vet checkups important for early cancer detection. Keep coat clean and dry to prevent hot spots.',
  },
  {
    id: 'french-bulldog',
    name: 'French Bulldog',
    group: 'Non-Sporting',
    size: 'Small',
    weight: '16-28 lbs',
    lifespan: '10-12 years',
    energy: 'Low-Medium',
    iconColor: '#9E9E9E',
    description: 'Playful, adaptable, and charming companion dog.',
    healthRisks: [
      { condition: 'Brachycephalic Syndrome', severity: 'serious', description: 'Breathing difficulties due to flat face' },
      { condition: 'Spinal Issues', severity: 'common', description: 'IVDD and other back problems' },
      { condition: 'Allergies', severity: 'common', description: 'Food and environmental allergies' },
      { condition: 'Heat Sensitivity', severity: 'serious', description: 'Cannot regulate temperature well - heat stroke risk' },
      { condition: 'Eye Problems', severity: 'moderate', description: 'Cherry eye and corneal ulcers' },
    ],
    careNotes: 'Never exercise in heat. Keep in air conditioning. Watch for labored breathing. Avoid stairs and jumping.',
  },
  {
    id: 'bulldog',
    name: 'Bulldog (English)',
    group: 'Non-Sporting',
    size: 'Medium',
    weight: '40-50 lbs',
    lifespan: '8-10 years',
    energy: 'Low',
    iconColor: '#D4793A',
    description: 'Calm, courageous, and friendly. Iconic wrinkled face.',
    healthRisks: [
      { condition: 'Brachycephalic Syndrome', severity: 'serious', description: 'Severe breathing issues common' },
      { condition: 'Hip Dysplasia', severity: 'common', description: 'Joint problems despite smaller size' },
      { condition: 'Skin Fold Infections', severity: 'common', description: 'Wrinkles need daily cleaning' },
      { condition: 'Heart Disease', severity: 'moderate', description: 'Pulmonic stenosis risk' },
      { condition: 'Heat Stroke', severity: 'serious', description: 'Very heat intolerant' },
    ],
    careNotes: 'Clean skin folds daily. Strict heat avoidance. May need surgery for breathing. No strenuous exercise.',
  },
  {
    id: 'poodle',
    name: 'Poodle (Standard)',
    group: 'Non-Sporting',
    size: 'Medium-Large',
    weight: '40-70 lbs',
    lifespan: '12-15 years',
    energy: 'High',
    iconColor: '#81C784',
    description: 'Highly intelligent, athletic, and hypoallergenic.',
    healthRisks: [
      { condition: 'Hip Dysplasia', severity: 'moderate', description: 'Less common than other large breeds' },
      { condition: 'Bloat (GDV)', severity: 'serious', description: 'Deep-chested breeds are at risk' },
      { condition: 'Addison\'s Disease', severity: 'moderate', description: 'Adrenal gland insufficiency' },
      { condition: 'Progressive Retinal Atrophy', severity: 'moderate', description: 'Can lead to blindness' },
      { condition: 'Epilepsy', severity: 'moderate', description: 'Seizure disorder in some lines' },
    ],
    careNotes: 'Regular grooming essential. Feed multiple small meals to reduce bloat risk. Mentally stimulating activities important.',
  },
  {
    id: 'beagle',
    name: 'Beagle',
    group: 'Hound',
    size: 'Small-Medium',
    weight: '20-30 lbs',
    lifespan: '12-15 years',
    energy: 'High',
    iconColor: '#D4793A',
    description: 'Merry, curious, and friendly scent hound.',
    healthRisks: [
      { condition: 'Obesity', severity: 'common', description: 'Food-driven breed prone to weight gain' },
      { condition: 'Epilepsy', severity: 'moderate', description: 'More common than in many breeds' },
      { condition: 'Hypothyroidism', severity: 'moderate', description: 'Thyroid gland underactivity' },
      { condition: 'Intervertebral Disc Disease', severity: 'moderate', description: 'Back problems, especially if overweight' },
      { condition: 'Cherry Eye', severity: 'common', description: 'Third eyelid gland prolapse' },
    ],
    careNotes: 'Strict portion control essential. Keep secure - they follow their nose. Regular exercise prevents obesity.',
  },
  {
    id: 'rottweiler',
    name: 'Rottweiler',
    group: 'Working',
    size: 'Large',
    weight: '80-135 lbs',
    lifespan: '8-10 years',
    energy: 'Medium-High',
    iconColor: '#7EC8C8',
    description: 'Confident, loyal, and protective guardian breed.',
    healthRisks: [
      { condition: 'Hip Dysplasia', severity: 'common', description: 'Very common - screening recommended' },
      { condition: 'Elbow Dysplasia', severity: 'common', description: 'Joint malformation issues' },
      { condition: 'Osteosarcoma', severity: 'serious', description: 'Bone cancer - higher incidence than average' },
      { condition: 'Heart Disease', severity: 'moderate', description: 'Subaortic stenosis risk' },
      { condition: 'Bloat (GDV)', severity: 'serious', description: 'Large, deep-chested breeds at risk' },
    ],
    careNotes: 'Early health screening important. Avoid rapid growth in puppies. Multiple small meals reduce bloat risk.',
  },
  {
    id: 'yorkshire-terrier',
    name: 'Yorkshire Terrier',
    group: 'Toy',
    size: 'Toy',
    weight: '4-7 lbs',
    lifespan: '12-15 years',
    energy: 'Medium',
    iconColor: '#D4793A',
    description: 'Feisty, affectionate, and sprightly toy breed.',
    healthRisks: [
      { condition: 'Luxating Patella', severity: 'common', description: 'Kneecap dislocation common in toy breeds' },
      { condition: 'Portosystemic Shunt', severity: 'serious', description: 'Liver blood vessel abnormality' },
      { condition: 'Tracheal Collapse', severity: 'moderate', description: 'Windpipe weakness causing coughing' },
      { condition: 'Dental Disease', severity: 'common', description: 'Small mouths prone to dental issues' },
      { condition: 'Hypoglycemia', severity: 'moderate', description: 'Low blood sugar, especially in puppies' },
    ],
    careNotes: 'Use harness instead of collar. Regular dental care essential. Feed frequent small meals to prevent low blood sugar.',
  },
  {
    id: 'dachshund',
    name: 'Dachshund',
    group: 'Hound',
    size: 'Small',
    weight: '11-32 lbs',
    lifespan: '12-16 years',
    energy: 'Medium',
    iconColor: '#D4793A',
    description: 'Clever, lively, and courageous with iconic long body.',
    healthRisks: [
      { condition: 'Intervertebral Disc Disease', severity: 'serious', description: 'Very high risk due to long back' },
      { condition: 'Obesity', severity: 'common', description: 'Extra weight stresses the spine' },
      { condition: 'Dental Disease', severity: 'common', description: 'Prone to tooth and gum problems' },
      { condition: 'Epilepsy', severity: 'moderate', description: 'Seizures occur in some lines' },
      { condition: 'Eye Problems', severity: 'moderate', description: 'PRA and cataracts can occur' },
    ],
    careNotes: 'Prevent jumping on/off furniture. Use ramps. Keep weight strictly controlled. Support back when carrying.',
  },
  {
    id: 'boxer',
    name: 'Boxer',
    group: 'Working',
    size: 'Medium-Large',
    weight: '50-80 lbs',
    lifespan: '10-12 years',
    energy: 'High',
    iconColor: '#D4793A',
    description: 'Fun-loving, bright, and active family companion.',
    healthRisks: [
      { condition: 'Cancer', severity: 'serious', description: 'Higher rates of various cancers' },
      { condition: 'Heart Disease', severity: 'serious', description: 'Boxer cardiomyopathy and aortic stenosis' },
      { condition: 'Hip Dysplasia', severity: 'moderate', description: 'Joint issues in some lines' },
      { condition: 'Bloat (GDV)', severity: 'serious', description: 'Deep chest puts them at risk' },
      { condition: 'Allergies', severity: 'common', description: 'Skin and food allergies frequent' },
    ],
    careNotes: 'Regular cardiac screening recommended. Avoid extreme temperatures. Multiple small meals to reduce bloat risk.',
  },
  {
    id: 'shih-tzu',
    name: 'Shih Tzu',
    group: 'Toy',
    size: 'Small',
    weight: '9-16 lbs',
    lifespan: '10-16 years',
    energy: 'Low-Medium',
    iconColor: '#9E9E9E',
    description: 'Affectionate, playful, and outgoing companion.',
    healthRisks: [
      { condition: 'Brachycephalic Syndrome', severity: 'moderate', description: 'Breathing issues due to flat face' },
      { condition: 'Eye Problems', severity: 'common', description: 'Prominent eyes prone to injury and dry eye' },
      { condition: 'Dental Disease', severity: 'common', description: 'Small mouth causes crowding' },
      { condition: 'Hip Dysplasia', severity: 'moderate', description: 'Surprisingly common for size' },
      { condition: 'Ear Infections', severity: 'common', description: 'Floppy ears trap moisture' },
    ],
    careNotes: 'Keep face hair trimmed. Clean eye area daily. Regular dental care. Keep ears clean and dry.',
  },
]
